CREATE TABLE IF NOT EXISTS `{PREFIX}plugins_thirdpartylogin_user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `user_id` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '用户id',
  `status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '状态（0未绑定, 1已绑定, 2已解绑）',
  `platform` char(30) NOT NULL DEFAULT '' COMMENT '平台类型（ dingding 钉钉 、 weixin 微信 、 qq QQ  alipay 支付宝 、 sina 新浪 ）',
  `openid` char(60) NOT NULL DEFAULT '' COMMENT 'openid',
  `unionid` char(60) NOT NULL DEFAULT '' COMMENT 'unionid',
  `nickname` char(60) NOT NULL DEFAULT '' COMMENT '用户昵称',
  `avatar` char(255) NOT NULL DEFAULT '' COMMENT '用户头像地址',
  `mobile` char(30) NOT NULL DEFAULT '' COMMENT '手机号码',
  `email` char(60) NOT NULL DEFAULT '' COMMENT '电子邮箱（最大长度60个字符）',
  `gender` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '性别（0保密，1女，2男）',
  `province` char(60) NOT NULL DEFAULT '' COMMENT '所在省',
  `city` char(60) NOT NULL DEFAULT '' COMMENT '所在市',
  `add_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '添加时间',
  `upd_time` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `status` (`status`),
  KEY `platform` (`platform`),
  KEY `openid` (`openid`),
  KEY `unionid` (`unionid`),
  KEY `add_time` (`add_time`)
) ENGINE=InnoDB DEFAULT CHARSET={CHARSET} ROW_FORMAT=DYNAMIC COMMENT='关联用户 - 第三方登录';